---
- name: Gather min facts
  ansible.builtin.setup:
    gather_subset: min
  
- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian']
