---
- name: Gather facts
  ansible.builtin.setup:
  
- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian']
